apiVersion: v1
kind: Pod
metadata:
  name: csi-workload
spec:
  containers:
  - name: app
    image: busybox
    imagePullPolicy: IfNotPresent
    args: [
      "sleep",
      "10000"
    ]
    volumeMounts:
    - name: my-csi-inline-vol
      mountPath: /mnt/csi
  volumes:
  - name: my-csi-inline-vol
    csi:
      driver: dummy-fuse-csi
