apiVersion: v1
kind: Pod
metadata:
  name: dummy-fuse-pod8
spec:
  containers:
  - name: dummy-workload
    image: busybox
    imagePullPolicy: IfNotPresent
    args: [
      "sleep",
      "10000"
    ]
    volumeMounts:
    - name: my-csi-inline-vol
      mountPath: /mnt
  # volumes:
  # - name: mypvc
  #   persistentVolumeClaim: 
  #     claimName: dummy-fuse-pvc
  #     readOnly: false
  volumes:
  - name: my-csi-inline-vol
    csi:
      driver: dummy-fuse-csi
